Traceback (most recent call last):
  File "creat_scr.pyo", line 356, in combin_handle
  File "config.pyo", line 82, in save_COMBIN_save_path
IOError: [Errno 2] No such file or directory: '.\\data\\datacust_path_save_path.ini'
